#! /usr/bin/env bash

# Balanced profile for use with Framework laptop (Intel i5-1240p)
# Tested with fw-fanctrl on 'medium' profile
#
# Main usecase: decent performance with little fan noise
# - 'decent' battery life
# - low fan noise
# - fairly responsive

# 3.3GHz clock speed limit
/run/current-system/sw/bin/cpupower --cpu all frequency-set --max 3.3GHz

# 12W PL1
echo 12000000 | tee /sys/class/powercap/intel-rapl/intel-rapl\:0/constraint_0_power_limit_uw

# 17W PL2
echo 17000000 | tee /sys/class/powercap/intel-rapl/intel-rapl\:0/constraint_1_power_limit_uw
