#! /usr/bin/env bash

# Powersave profile for use with Framework laptop (Intel i5-1240p)
# Tested with fw-fanctrl on 'medium' profile
#
# Main usecase: light workload on battery
# - 'long' battery life
# - silent operation
# - noticeably less responsive for simple tasks

# 2.2GHz clock speed limit
cpupower --cpu all frequency-set --max 2.2GHz

# 9W flat package power limit
echo 9000000 | tee /sys/class/powercap/intel-rapl/intel-rapl\:0/constraint_0_power_limit_uw
echo 9000000 | tee /sys/class/powercap/intel-rapl/intel-rapl\:0/constraint_1_power_limit_uw
